

name: publish

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  OCI_REPO: "oci://ghcr.io/weaveworks/${{ github.event.repository.name }}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow removes the thanos url on cluster deletion
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push manifests
        run: |
          cd terraform
          flux push artifact $OCI_REPO:$(git rev-parse --short HEAD) \
            --path="./" \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)/$(git rev-parse HEAD)"
      - name: Tag latest
        run: |
          flux tag artifact $OCI_REPO:$(git rev-parse --short HEAD) --tag latest